USE DATABASE ABC;
USE SCHEMA POLICY_SCHEMA;

-- ============================================
-- RAW_CLAIMS DATA QUALITY ANALYSIS
-- ============================================

-- 1. Total rows
SELECT 'TOTAL_ROWS' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS;

-- 2. NULL key fields
SELECT 'NULL_CLAIM_ID' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE claim_id IS NULL OR TRIM(claim_id) = '';
SELECT 'NULL_POLICY_NUMBER' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE policy_number IS NULL OR TRIM(policy_number) = '';
SELECT 'NULL_CUSTOMER_ID' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE customer_id IS NULL OR TRIM(customer_id) = '';

-- 3. Duplicate claim IDs
SELECT 'DUPLICATE_CLAIM_ID' AS CHECK_NAME, COUNT(*) AS CNT FROM (SELECT claim_id FROM RAW_CLAIMS GROUP BY claim_id HAVING COUNT(*) > 1);
SELECT 'DUPLICATE_CLAIM_ROWS' AS CHECK_NAME, claim_id, COUNT(*) AS CNT FROM RAW_CLAIMS GROUP BY claim_id HAVING COUNT(*) > 1;

-- 4. State inconsistency (UP vs Uttar Pradesh)
SELECT 'STATE_VALUES' AS CHECK_NAME, TRIM(state) AS state_clean, COUNT(*) AS CNT FROM RAW_CLAIMS GROUP BY TRIM(state) ORDER BY CNT DESC;

-- 5. ZIP issues
SELECT 'ZIP_MISSING' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE zip IS NULL OR TRIM(zip) = '';
SELECT 'ZIP_NON_NUMERIC' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE zip IS NOT NULL AND TRIM(zip) != '' AND NOT REGEXP_LIKE(TRIM(zip), '^[0-9]+$');
SELECT 'BAD_ZIP_SAMPLES' AS CHECK_NAME, TRIM(zip) AS zip_val, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE zip IS NOT NULL AND TRIM(zip) != '' AND NOT REGEXP_LIKE(TRIM(zip), '^[0-9]{6}$') GROUP BY TRIM(zip) ORDER BY CNT DESC LIMIT 20;

-- 6. Date format inconsistency
SELECT 'INCIDENT_DATE_SLASH' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE incident_date LIKE '%/%';
SELECT 'INCIDENT_DATE_DASH' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE incident_date LIKE '%-%';

-- 7. Claim status values
SELECT 'STATUS_VALUES' AS CHECK_NAME, status, COUNT(*) AS CNT FROM RAW_CLAIMS GROUP BY status ORDER BY CNT DESC;

-- 8. Claim type values
SELECT 'CLAIM_TYPE_VALUES' AS CHECK_NAME, claim_type, COUNT(*) AS CNT FROM RAW_CLAIMS GROUP BY claim_type ORDER BY CNT DESC;

-- 9. Report channel values
SELECT 'CHANNEL_VALUES' AS CHECK_NAME, report_channel, COUNT(*) AS CNT FROM RAW_CLAIMS GROUP BY report_channel ORDER BY CNT DESC;

-- 10. Amount issues
SELECT 'INCURRED_MISSING' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE total_incurred IS NULL OR TRIM(total_incurred) = '';
SELECT 'INCURRED_NEGATIVE' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE total_incurred LIKE '-%';
SELECT 'PAID_MISSING' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE total_paid IS NULL OR TRIM(total_paid) = '';
SELECT 'PAID_NEGATIVE' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS WHERE total_paid LIKE '-%';

-- 11. Paid > Incurred (overpayment)
SELECT 'PAID_EXCEEDS_INCURRED' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS
WHERE total_incurred IS NOT NULL AND TRIM(total_incurred) != ''
  AND total_paid IS NOT NULL AND TRIM(total_paid) != ''
  AND TRY_TO_DOUBLE(REPLACE(total_paid,',','')) > TRY_TO_DOUBLE(REPLACE(total_incurred,',',''));

-- 12. Orphan claims (policy_number not in RAW_POLICIES)
SELECT 'ORPHAN_CLAIMS' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_CLAIMS c
WHERE c.policy_number IS NOT NULL AND TRIM(c.policy_number) != ''
  AND NOT EXISTS (SELECT 1 FROM RAW_POLICIES p WHERE p.policy_number = c.policy_number);
