USE DATABASE ABC;
USE SCHEMA POLICY_SCHEMA;

-- ============================================
-- RAW_POLICIES DATA QUALITY ANALYSIS
-- ============================================

-- 1. Total row count
SELECT 'TOTAL_ROWS' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES;

-- 2. NULL / EMPTY key fields
SELECT 'NULL_POLICY_NUMBER' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE policy_number IS NULL OR TRIM(policy_number) = '';
SELECT 'NULL_CUSTOMER_ID' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE customer_id IS NULL OR TRIM(customer_id) = '';

-- 3. Duplicate policy numbers
SELECT 'DUPLICATE_POLICY_NUMBER' AS CHECK_NAME, COUNT(*) AS CNT FROM (SELECT policy_number FROM RAW_POLICIES GROUP BY policy_number HAVING COUNT(*) > 1);

-- 4. SSN format issues (should be XXX-XX-XXXX)
SELECT 'SSN_BAD_FORMAT' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE ssn IS NOT NULL AND TRIM(ssn) != '' AND NOT REGEXP_LIKE(TRIM(ssn), '^[0-9]{3}-[0-9]{2}-[0-9]{4}$');

-- 5. Email issues (leading/trailing spaces, missing @)
SELECT 'EMAIL_WHITESPACE' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE email IS NOT NULL AND (email != TRIM(email));
SELECT 'EMAIL_MISSING_OR_INVALID' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE email IS NULL OR TRIM(email) = '' OR NOT REGEXP_LIKE(TRIM(email), '.*@.*\\..*');

-- 6. Phone missing or empty
SELECT 'PHONE_MISSING' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE phone IS NULL OR TRIM(phone) = '';

-- 7. Address / City / State whitespace issues
SELECT 'CITY_WHITESPACE' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE city IS NOT NULL AND city != TRIM(city);
SELECT 'STATE_WHITESPACE' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE state IS NOT NULL AND state != TRIM(state);

-- 8. ZIP code issues (non-numeric, hyphens, alpha chars)
SELECT 'ZIP_MISSING' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE zip IS NULL OR TRIM(zip) = '';
SELECT 'ZIP_NON_NUMERIC' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE zip IS NOT NULL AND TRIM(zip) != '' AND NOT REGEXP_LIKE(TRIM(zip), '^[0-9]+$');

-- 9. Inconsistent date formats (YYYY/MM/DD vs YYYY-MM-DD)
SELECT 'EFFECTIVE_DATE_SLASH' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE effective_date LIKE '%/%';
SELECT 'EFFECTIVE_DATE_DASH' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE effective_date LIKE '%-%';
SELECT 'EXPIRATION_DATE_SLASH' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE expiration_date LIKE '%/%';
SELECT 'EXPIRATION_DATE_DASH' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE expiration_date LIKE '%-%';

-- 10. Premium with commas (not numeric as-is)
SELECT 'PREMIUM_HAS_COMMA' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE annual_premium LIKE '%,%';
SELECT 'PREMIUM_MISSING' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE annual_premium IS NULL OR TRIM(annual_premium) = '';
SELECT 'PREMIUM_NEGATIVE' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE annual_premium LIKE '-%';

-- 11. Renewal flag inconsistency (Y/y/N/n/1/0 etc.)
SELECT 'RENEWAL_FLAG_VALUES' AS CHECK_NAME, renewal_flag, COUNT(*) AS CNT FROM RAW_POLICIES GROUP BY renewal_flag ORDER BY CNT DESC;

-- 12. Policy type distinct values
SELECT 'POLICY_TYPE_VALUES' AS CHECK_NAME, policy_type, COUNT(*) AS CNT FROM RAW_POLICIES GROUP BY policy_type ORDER BY CNT DESC;

-- 13. Policy status distinct values
SELECT 'POLICY_STATUS_VALUES' AS CHECK_NAME, policy_status, COUNT(*) AS CNT FROM RAW_POLICIES GROUP BY policy_status ORDER BY CNT DESC;

-- 14. Payment frequency distinct values
SELECT 'PAYMENT_FREQ_VALUES' AS CHECK_NAME, payment_frequency, COUNT(*) AS CNT FROM RAW_POLICIES GROUP BY payment_frequency ORDER BY CNT DESC;

-- 15. Marital status distinct values
SELECT 'MARITAL_STATUS_VALUES' AS CHECK_NAME, marital_status, COUNT(*) AS CNT FROM RAW_POLICIES GROUP BY marital_status ORDER BY CNT DESC;

-- 16. Agency region distinct values
SELECT 'AGENCY_REGION_VALUES' AS CHECK_NAME, agency_region, COUNT(*) AS CNT FROM RAW_POLICIES GROUP BY agency_region ORDER BY CNT DESC;

-- 17. State name inconsistency (UP vs Uttar Pradesh etc.)
SELECT 'STATE_VALUES' AS CHECK_NAME, TRIM(state) AS state_clean, COUNT(*) AS CNT FROM RAW_POLICIES GROUP BY TRIM(state) ORDER BY CNT DESC;

-- 18. Sample bad ZIP values
SELECT 'BAD_ZIP_SAMPLES' AS CHECK_NAME, TRIM(zip) AS zip_val, COUNT(*) AS CNT FROM RAW_POLICIES WHERE zip IS NOT NULL AND TRIM(zip) != '' AND NOT REGEXP_LIKE(TRIM(zip), '^[0-9]{6}$') GROUP BY TRIM(zip) ORDER BY CNT DESC LIMIT 20;

-- 19. Sample bad SSN values
SELECT 'BAD_SSN_SAMPLES' AS CHECK_NAME, ssn, COUNT(*) AS CNT FROM RAW_POLICIES WHERE ssn IS NOT NULL AND TRIM(ssn) != '' AND NOT REGEXP_LIKE(TRIM(ssn), '^[0-9]{3}-[0-9]{2}-[0-9]{4}$') GROUP BY ssn ORDER BY CNT DESC LIMIT 10;

-- 20. Expiration before Effective date
SELECT 'EXPIRY_BEFORE_EFFECTIVE' AS CHECK_NAME, COUNT(*) AS CNT FROM RAW_POLICIES WHERE TRY_TO_DATE(REPLACE(expiration_date,'/','-')) < TRY_TO_DATE(REPLACE(effective_date,'/','-'));
