USE DATABASE ABC;
USE SCHEMA POLICY_SCHEMA;

-- Count pipes
SHOW PIPES IN SCHEMA POLICY_SCHEMA;
SELECT COUNT(*) AS PIPE_COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- Count streams
SHOW STREAMS IN SCHEMA POLICY_SCHEMA;
SELECT COUNT(*) AS STREAM_COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- Task names and states
SHOW TASKS IN SCHEMA POLICY_SCHEMA;
SELECT "name" AS TASK_NAME, "state" AS STATE FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) ORDER BY "name";
