USE DATABASE ABC;
USE SCHEMA POLICY_SCHEMA;

-- ============================================
-- SILVER_POLICY_CLEANED_DATA VALIDATION
-- ============================================

SELECT '--- POLICY SILVER CHECKS ---' AS SECTION;

SELECT 'TOTAL_ROWS' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA;

-- Key fields
SELECT 'NULL_POLICY_NUMBER' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE policy_number IS NULL OR policy_number = '';
SELECT 'NULL_CUSTOMER_ID' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE customer_id IS NULL OR customer_id = '';

-- SSN after fix
SELECT 'SSN_STILL_BAD' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE is_ssn_valid = FALSE;
SELECT 'SSN_SAMPLE_FIXED' AS CHECK_NAME, ssn FROM SILVER_POLICY_CLEANED_DATA WHERE is_ssn_valid = TRUE LIMIT 3;
SELECT 'SSN_SAMPLE_BAD' AS CHECK_NAME, ssn FROM SILVER_POLICY_CLEANED_DATA WHERE is_ssn_valid = FALSE LIMIT 5;

-- Email after fix
SELECT 'EMAIL_STILL_INVALID' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE is_email_valid = FALSE;
SELECT 'EMAIL_STILL_WHITESPACE' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE email IS NOT NULL AND email != TRIM(email);

-- Phone
SELECT 'PHONE_STILL_MISSING' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE is_phone_valid = FALSE;

-- State after normalization
SELECT 'STATE_VALUES_AFTER' AS CHECK_NAME, state, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA GROUP BY state ORDER BY CNT DESC;

-- ZIP after fix
SELECT 'ZIP_INVALID_COUNT' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE is_zip_valid = FALSE;
SELECT 'ZIP_NULL' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE zip IS NULL;
SELECT 'ZIP_BAD_SAMPLES' AS CHECK_NAME, zip, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE is_zip_valid = FALSE AND zip IS NOT NULL GROUP BY zip ORDER BY CNT DESC LIMIT 10;

-- Dates (should all be proper DATE now)
SELECT 'EFF_DATE_NULL' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE effective_date IS NULL;
SELECT 'EXP_DATE_NULL' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE expiration_date IS NULL;

-- Premium
SELECT 'PREMIUM_NULL' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE annual_premium IS NULL;
SELECT 'PREMIUM_NEGATIVE' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA WHERE annual_premium < 0;

-- Renewal flag
SELECT 'RENEWAL_VALUES' AS CHECK_NAME, renewal_flag, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA GROUP BY renewal_flag ORDER BY CNT DESC;

-- Payment freq
SELECT 'PAY_FREQ_VALUES' AS CHECK_NAME, payment_frequency, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA GROUP BY payment_frequency ORDER BY CNT DESC;

-- Policy status
SELECT 'STATUS_VALUES' AS CHECK_NAME, policy_status, COUNT(*) AS CNT FROM SILVER_POLICY_CLEANED_DATA GROUP BY policy_status ORDER BY CNT DESC;


-- ============================================
-- SILVER_CLAIMS_CLEANED_DATA VALIDATION
-- ============================================

SELECT '--- CLAIMS SILVER CHECKS ---' AS SECTION;

SELECT 'TOTAL_ROWS' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA;

-- Duplicates
SELECT 'DUPLICATE_CLAIM_IDS' AS CHECK_NAME, claim_id, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA GROUP BY claim_id HAVING COUNT(*) > 1;

-- Nulls
SELECT 'NO_POLICY_LINK' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA WHERE has_policy_link = FALSE;

-- State
SELECT 'STATE_VALUES_AFTER' AS CHECK_NAME, state, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA GROUP BY state ORDER BY CNT DESC;

-- ZIP
SELECT 'ZIP_INVALID_COUNT' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA WHERE is_zip_valid = FALSE;
SELECT 'ZIP_BAD_SAMPLES' AS CHECK_NAME, zip, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA WHERE is_zip_valid = FALSE AND zip IS NOT NULL GROUP BY zip ORDER BY CNT DESC LIMIT 10;

-- Dates
SELECT 'INCIDENT_DATE_NULL' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA WHERE incident_date IS NULL;

-- Amounts
SELECT 'INCURRED_NULL' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA WHERE total_incurred IS NULL;
SELECT 'PAID_NULL' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA WHERE total_paid IS NULL;
SELECT 'PAID_NEGATIVE' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA WHERE is_paid_negative = TRUE;
SELECT 'OVERPAID' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA WHERE is_overpaid = TRUE;

-- Orphan check
SELECT 'ORPHAN_CLAIMS' AS CHECK_NAME, COUNT(*) AS CNT FROM SILVER_CLAIMS_CLEANED_DATA c
WHERE c.policy_number IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SILVER_POLICY_CLEANED_DATA p WHERE p.policy_number = c.policy_number);
